### ISSUE TITLE
error: conflict with libwrapper

### ISSUE THREAD

**Issue by rinnocenti** [NekroDarkmoon/ammo-tracker-fvtt#11]
![image](https://user-images.githubusercontent.com/3178127/142646923-4de98d27-007c-4382-853e-a9c61ca0eceb.png)

**Comment by NekroDarkmoon** [comment]
Does this happen everytime?

**Comment by rinnocenti** [comment]
yes it's been a long time that I have had this error. (since the last version) i thought this one would fix, but it continues.

**Comment by rinnocenti** [comment]
the error appears at the end of the fight, but when it starts there is another error. (in the same scope)

**Comment by NekroDarkmoon** [comment]
Can you send that one too^^.

**Comment by NekroDarkmoon** [comment]
It seems like there's an actor id that is incorrect somewhere.

**Comment by Indoril007** [comment]
I also get this error. Downgrading to version 0.1.4 fixed it for me though.

**Comment by NekroDarkmoon** [comment]
Hmm, weird I thought I fixed this issue. I'll take a look at it this week

**Comment by Indoril007** [comment]
This is on foundry 0.8.9 by the way

**Comment by NekroDarkmoon** [comment]
Is there possibly an "item" in the combat that isn't an actor?
