### ISSUE TITLE
Disable tracking for specific ammunition

### ISSUE THREAD

**Issue by Nordiii** [NekroDarkmoon/ammo-tracker-fvtt#12]
Hello, a feature where you can set Ammunition that should not be tracked, like one use magic arrows would be awesome!

**Comment by w1face** [comment]
> I can make it so that just magic ammunition isn't tracked

Did this happen in the end?

**Comment by NekroDarkmoon** [comment]
Not yet. I'm currently in the process of migrating all my modules to V10. And I'm expecting to add this with that along with a few other changes

**Comment by NekroDarkmoon** [comment]
So taking a look at this today. There's no way to distinguish between a regular arrow and a magical arrow in the system. And if you want to omit magical ammuniton you could set it up to just not be consumed.

**Comment by NekroDarkmoon** [comment]
So I've added an experimental solution for this. The tracker will no longer track ammunition that isn't of the common rarity by default. This can be changed in the settings.

**Comment by NekroDarkmoon** [comment]
https://github.com/NekroDarkmoon/ammo-tracker-fvtt/releases/tag/0.3.0
