### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Gib2024** [NekroDarkmoon/ammo-tracker-fvtt#19]
Ran a combat last night and it was not taking off arrows or bolts.  I checked configuration but it only has magic ammo option.  Is there something I need to do or check?

Thanks!
Gib

**Comment by NekroDarkmoon** [comment]
Are you on dnd v 3.x if so there was new update released last night to fix compatibility

**Comment by NekroDarkmoon** [comment]
Also the module only automates the recovery of ammo. Consumption is handled by core

**Comment by Gib2024** [comment]
Not core but dnd 5e items have a missing code base.  Apparently after you
buy a bow and put it on your character you have to edit it and click
details and choose arrows as the consumed resource with a count of 1.  Big
oversight in the SRD programmers part.  Took me several hours researching
why my bow attacks were not consuming ammo! :(

Anyway thanks for your replies on your mod, much appreciated!!
