### ISSUE TITLE
Foundry v12 compatibility

### ISSUE THREAD

**Issue by unvrtz** [NekroDarkmoon/ammo-tracker-fvtt#20]
Thanks for your module. 
Is it possible to add Foundry v12 compatibility as v12 Stable is already released?

**Comment by VirusNik21** [comment]
> Thanks for your module. Is it possible to add Foundry v12 compatibility as v12 Stable is already released?

You can manually adjust module.json by changing the maximum FVTT version and the module will work correctly. I haven't noticed any errors yet.

**Comment by NekroDarkmoon** [comment]
Hunh I thought I had already done this. Guess not...

Will try and get an update out this week or next.

**Comment by Fridan99** [comment]
Any news about v12 compatibility? :P
