### ISSUE TITLE
Settings File Bloat and Hangs when creating Encounters

### ISSUE THREAD

**Issue by xaukael** [NekroDarkmoon/ammo-tracker-fvtt#8]
Your implementation is insane. I do not know if you intended to do this, but you are copying every combatant to the settings.db file when you start the tracking. This causes the game to hang when you are setting up combat. 

Also, the cleanup of the mess this makes does not work. This causes settings file to bloat making creating combat encounters to stall longer and longer each time.

**Comment by NekroDarkmoon** [comment]
Yeah, I'm aware of this issue. I've been meaning to fix it for a while but haven't gotten around to it. I do have another implementation of it partially finished.

**Comment by NekroDarkmoon** [comment]
Fixed in v2
